#!/bin/sh

# Try to run i3status-rs, or fallback on i3status
#
# https://github.com/greshake/i3status-rust

set -e

I3STATUS="i3status"
I3STATUS_CONFIG="${HOME}/.config/i3/i3status.conf"
I3STATUS_RS="${HOME}/.cargo/bin/i3status-rs"
I3STATUS_RS_CONFIG="${HOME}/.config/i3/i3status.toml"

if [ -f "${I3STATUS_CONFIG}.local" ]; then
    I3STATUS_CONFIG="${I3STATUS_CONFIG}.local"
fi

if [ -x ${I3STATUS_RS} ]; then
    exec ${I3STATUS_RS} "${I3STATUS_RS_CONFIG}"
else
    exec ${I3STATUS} -c "${I3STATUS_CONFIG}"
fi
