# https://github.com/Homebrew/homebrew-bundle

tap 'homebrew/cask'
tap 'wez/wezterm'

brew 'ag'
brew 'asdf'
brew 'awscli'
brew 'bash'
brew 'bat'
brew 'cmake'
brew 'coreutils'
brew 'curl'
brew 'exa'
brew 'findutils'
brew 'fzf'
brew 'git'
brew 'git-delta'
brew 'git-lfs'
brew 'glab'
brew 'gnu-sed'
brew 'gnu-tar'
brew 'gnupg'
brew 'goenv', args: ['HEAD']
brew 'gpatch'
brew 'graphicsmagick'
brew 'grep'
brew 'helm'
brew 'helmfile'
brew 'htop'
brew 'hub'
brew 'jq'
brew 'jsonnet'
brew 'jsonnet-bundler'
brew 'k9s'
brew 'kubernetes-cli'
brew 'kubectx'
brew 'lesspipe'
brew 'lftp'
brew 'libarchive'
brew 'mas'
brew 'minikube'
brew 'nvm'
brew 'openssh'
brew 'pinentry'
brew 'pinentry-mac'
brew 'postgresql'
brew 'pwgen'
brew 'pyenv'
brew 'rbenv'
brew 'ripgrep'
brew 'shellcheck'
brew 'sipcalc'
brew 'sshuttle'
brew 'tanka'
brew 'terraform-docs'
brew 'tfenv'
brew 'tmux'
brew 'vim'
brew 'wget'
brew 'xh'
brew 'xz'
brew 'yadm'
brew 'yarn'
brew 'ykman'
brew 'yq'
brew 'zsh'

cask '1password-cli'
cask 'chef-workstation'
cask 'keybase', greedy: true
cask 'wezterm', args: { no_quarantine: true }

local_brewfile=File.join(ENV['HOME'], '.Brewfile.local')
eval(IO.read(local_brewfile), binding) if File.exist?(local_brewfile)
