---
stages:
  - test

include:
  - template: Security/Secret-Detection.gitlab-ci.yml

vint:
  stage: test
  image: alpine:3.17
  script:
    - apk add py3-setuptools vint
    - vint --color --warning .vim/vimrc

shellcheck:
  stage: test
  image: koalaman/shellcheck-alpine:v0.9.0
  allow_failure: true
  script:
    - |
      status=0
      for file in \
          .bash_profile \
          .bashrc \
          .local/bin/sensible-browser \
          .local/bin/x-terminal-emulator \
          .profile \
          .xserverrc \
          .xsession \
          $(find .sh/inc -type f -name '*.sh'); do
        shellcheck --severity=warning "${file}" || status=1
      done
      exit ${status}
