'$schema' = 'https://starship.rs/config-schema.json'

# Disabled until fixed, workaround in fish config
# https://github.com/starship/starship/issues/560#issuecomment-2409922650
add_newline = false

format = """
[](fg:surface0)\
$os\
[( $username([@](bg:surface0 fg:text)$hostname) )](bg:surface0)\
[](fg:surface0 bg:surface1)\
$directory\
[](fg:surface1 bg:sky)\
$git_branch\
$git_commit\
[](fg:sky bg:blue)\
$git_state\
$git_status\
[](fg:blue bg:lavender)\
$cmd_duration\
$status\
[ ](fg:lavender)\
$line_break$character"""

palette = 'catppuccin_mocha'

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"

[character]
error_symbol = '[❯](bold fg:red)'
success_symbol = '[❯](bold fg:green)'
vimcmd_replace_one_symbol = '[❮](bold fg:mauve)'
vimcmd_replace_symbol = '[❮](bold fg:mauve)'
vimcmd_symbol = '[❮](bold fg:green)'
vimcmd_visual_symbol = '[❮](bold fg:peach)'

[cmd_duration]
format = '[  $duration]($style)'
style = 'fg:surface0 bg:lavender'

[directory]
fish_style_pwd_dir_length = 2
format = '[ $path[$read_only]($read_only_style) ]($style)'
home_symbol = ' '
read_only = ' 󰌾'
read_only_style = 'fg:red bg:surface1'
style = 'fg:blue bg:surface1'
truncation_length = 3
truncation_symbol = '…/'
truncate_to_repo = true

[directory.substitutions]
'Desktop' = ' '
'Documents' = '󰈙 '
'Downloads' = ' '
'Movies' = '󰿎 '
'Music' = '󰝚 '
'Pictures' = ' '
'Videos' = '󰿎 '

[git_branch]
format = '[ $symbol$branch(  $remote_branch) ]($style)'
style = 'fg:surface0 bg:sky'
symbol = ' '

[git_commit]
format = '[ $hash$tag ]($style)'
style = 'fg:surface0 bg:sky'
tag_symbol = '  '
tag_disabled = false

[git_state]
format = '[ \($state( $progress_current/$progress_total)\)]($style)'
style = 'fg:surface0 bg:blue'

[git_status]
format = '[( $all_status$ahead_behind)]($style)'
style = 'fg:surface0 bg:blue'

ahead = ' $count '
behind = ' $count '
conflicted = ' $count '
deleted = ' $count '
diverged = ' $ahead_count  $behind_count '
modified = ' $count '
renamed = ' $count '
staged = ' $count '
stashed = ' $count '
untracked = ' '
up_to_date = ''

[hostname]
format = '[$hostname]($style)'
ssh_symbol = ' '
ssh_only = true
style = 'bg:surface0 fg:green'

[line_break]
disabled = false

[os]
disabled = false
format = '[$symbol]($style)'
style = 'bg:surface0 fg:text'

[os.symbols]
Android = ' '
Arch = ' '
Debian = ' '
Linux = ' '
Macos = ' '
Ubuntu = ' '
Unknown = ' '
Windows = '󰍲 '

[status]
disabled = false
format = '[ $symbol ($common_meaning$maybe_int )(\(SIG$signal_name:$signal_number\) )]($style)'
map_symbol = true
not_executable_symbol = ''
not_found_symbol = ''
pipestatus = true
pipestatus_format = '[ $pipestatus $symbol ($common_meaning$maybe_int )(\(SIG$signal_name:$signal_number\) )]($style)'
sigint_symbol = ''
signal_symbol = ''
style = 'fg:surface0 bg:lavender'
success_symbol = ''
symbol = ''

[username]
format = '[$user]($style)'
show_always = false
style_user = 'bg:surface0 fg:blue'
style_root = 'bg:surface0 fg:red bold'
