# man 5 fuzzel.ini

anchor=center
font=MonaspiceAr Nerd Font:size=11
icon-theme=Papirus-Dark
line-height=24
lines=8
match-mode=fzf
prompt=" "
terminal=sensible-terminal -e
width=32

[colors]
# Catppuccin Mocha - Blue
# https://github.com/catppuccin/fuzzel
background=1e1e2ebf
text=cdd6f4ff
prompt=bac2deff
placeholder=7f849cff
input=cdd6f4ff
match=89b4faff
selection=585b70ff
selection-text=cdd6f4ff
selection-match=89b4faff
counter=7f849cff
border=89b4faff

[border]
radius=8
width=1
