# man 5 fuzzel.ini

anchor=center
font=MonaspiceAr Nerd Font:size=11
icon-theme=Nordzy-dark
line-height=24
lines=8
match-mode=fzf
prompt=" "
terminal=sensible-terminal -e
width=32

[colors]
# Nord color palette
background=2e3440bf      # Nord0
text=d8dee9ff            # Nord4
message=#88c0d0ff        # Nord8
prompt=4c566aff          # Nord3
placeholder=4c566aff     # Nord3
input=8fbcbbff           # Nord7
match=ebcb8bff           # Nord13
selection=3b4252ff       # Nord1
selection-text=eceff4ff  # Nord6
selection-match=b48eadff # Nord15
counter=4c566aff         # Nord3
border=4c566aff          # Nord3

[border]
radius=8
width=1
