#!/bin/sh

: "${XDG_CONFIG_HOME:=${HOME}/.config}"
# shellcheck source=/dev/null
. "${ENV:-${XDG_CONFIG_HOME}/sh/profile}"

# Submodules

echo ' Updating submodules...'
yadm -C "${HOME}" submodule update --init --recursive

# Homebrew

if [ "$(uname -s)" = 'Darwin' ]; then
  brewfile="${XDG_CONFIG_HOME}/homebrew/Brewfile"
  brewfile_lock_json="${brewfile}.lock.json"
  # shellcheck disable=SC3013
  if ! [ -f "${brewfile_lock_json}" ] || [ "${brewfile}" -nt "${brewfile_lock_json}" ]; then
    echo '🍺Updating Homebrew bundle...'
    brew bundle --file "${brewfile}" --verbose
  fi
  unset brewfile brewfile_lock_json

  if ! [ -L "${XDG_DATA_HOME}/terminfo/t/tmux-256color" ]; then
    echo ' Installing modified Tmux terminfo file for OSX...'
    mkdir -p "${XDG_DATA_HOME}/terminfo/t"
    ln -sf "${XDG_CONFIG_HOME}/tmux/terminfo/tmux-256color" "${XDG_DATA_HOME}/terminfo/t/tmux-256color"
  fi
fi

# SSH

echo ' Updating SSH authorized keys...'
mkdir -p "${HOME}/.ssh"
cat "${XDG_CONFIG_HOME}/ssh/authorized_keys"/* > "${HOME}/.ssh/authorized_keys"

# Vim

if ! [ -f "${XDG_DATA_HOME}/vim/autoload/plug.vim" ]; then
  echo ' Setting up vim-plug...'
  curl -sfLo "${XDG_DATA_HOME}/vim/autoload/plug.vim" --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
else
  echo ' Ensuring vim-plug is up-to-date...'
  vim -es -N -u "${XDG_CONFIG_HOME}/vim/vimrc" -i NONE '+PlugUpgrade' '+qall'
fi

echo ' Updating all Vim plugins...'
vim -es -N -u "${XDG_CONFIG_HOME}/vim/vimrc" -i NONE '+PlugClean!' '+PlugUpdate' '+qall'

# ZSH

if ! [ -d "${XDG_DATA_HOME}/zsh/antidote" ]; then
  echo ' Installing antidote...'
  git clone --quiet --depth=1 https://github.com/mattmc3/antidote.git \
    "${XDG_DATA_HOME}/zsh/antidote"
else
  echo ' Ensuring antidote is up-to-date...'
  git -C "${XDG_DATA_HOME}/zsh/antidote" pull --quiet
fi

# vim:filetype=sh:tabstop=2:shiftwidth=2:fdm=marker:
