#!/bin/sh

# Local xsession script additions
# Can use `exec something` to launch a different WM instead of i3
if [ -f "${XDG_CONFIG_HOME}/.config/X11/xsession.local" ]; then
  # shellcheck source=/dev/null
  . "${XDG_CONFIG_HOME}/.config/X11/xsession.local"
fi

# i3
exec i3 || echo 'Failed to launch i3'

# vim:ft=sh:sw=2:
