" {{{ force use of a POSIX shell

set shell=/bin/sh

" }}}

" {{{ XDG

if empty($XDG_CONFIG_HOME) | let $XDG_CONFIG_HOME = HOME . '.config' | endif
if empty($XDG_DATA_HOME) | let $XDG_DATA_HOME = HOME . '.local/share' | endif
if empty($XDG_STATE_HOME) | let $XDG_STATE_HOME = HOME . '.local/state' | endif

set runtimepath^=${XDG_CONFIG_HOME}/vim
set runtimepath+=${XDG_DATA_HOME}/vim
set runtimepath+=${XDG_CONFIG_HOME}/vim/after

set packpath^=${XDG_DATA_HOME}/vim,${XDG_CONFIG_HOME}/vim
set packpath+=${XDG_CONFIG_HOME}/vim/after,${XDG_DATA_HOME}/vim/after

let g:netrw_home = $XDG_DATA_HOME.'/vim'
call mkdir($XDG_DATA_HOME.'/vim/spell', 'p')

set backupdir=${XDG_STATE_HOME}/vim/backup | call mkdir(&backupdir, 'p')
set directory=${XDG_STATE_HOME}/vim/swap   | call mkdir(&directory, 'p')
set undodir=${XDG_STATE_HOME}/vim/undo     | call mkdir(&undodir,   'p')
set viewdir=${XDG_STATE_HOME}/vim/view     | call mkdir(&viewdir,   'p')

if !has('nvim') | set viminfofile=${XDG_STATE_HOME}/vim/viminfo | endif

" }}}

" {{{ vim-plug (https://github.com/junegunn/vim-plug)

let data_dir = has('nvim') ? stdpath('data') . '/site' : $XDG_DATA_HOME.'/vim'
if empty(glob(data_dir . '/autoload/plug.vim'))
  silent execute '!curl -sfLo '.data_dir.'/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
  augroup vim_plug_init
    autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
  augroup END
endif
unlet data_dir

source ${XDG_CONFIG_HOME}/vim/plugins.vim

augroup vim_plug_start
  autocmd VimEnter *
    \  if len(filter(values(g:plugs), '!isdirectory(v:val.dir)'))
    \|   PlugInstall --sync | q
    \| endif
augroup END

" }}}

" {{{ Enable syntax

filetype plugin indent on
syntax on

" }}}

" {{{ Colors

if has('terminfo') || has('nvim')
  set background=dark
  if exists('+termguicolors')
    if &term =~# 'xterm\|wezterm\|tmux'
      " https://github.com/tmux/tmux/issues/1246
      let &t_8f="\e[38;2;%lu;%lu;%lum"
      let &t_8b="\e[48;2;%lu;%lu;%lum"
      " https://gist.github.com/gutoyr/4192af1aced7a1b555df06bd3781a722
      let &t_ZH="\e[3m"
      let &t_ZR="\e[23m"
      " Strikethrough
      let &t_Ts="\e[9m"
      let &t_Te="\e[29m"
      " Undercurl
      let &t_Cs="\e[4:3m"
      let &t_Ce="\e[4:0m"
    endif
    set termguicolors
  endif
  " https://www.nordtheme.com/docs/ports/vim/configuration
  let g:nord_bold=1
  let g:nord_italic=1
  let g:nord_italic_comments=1
  let g:nord_underline=1
  let g:nord_uniform_diff_background=1
  augroup nord-theme-overrides
    autocmd!
    autocmd ColorScheme nord highlight normal guibg=NONE ctermbg=NONE
    autocmd ColorScheme nord highlight SpellBad cterm=undercurl
    autocmd ColorScheme nord highlight SpellCap cterm=undercurl
    autocmd ColorScheme nord highlight SpellLocal cterm=undercurl
    autocmd ColorScheme nord highlight SpellRare cterm=undercurl
  augroup END
  colorscheme nord
end

" }}}

" {{{ Various basic settings

set modeline
set modelines=3

set backspace=indent,eol,start

set nobackup
set noundofile
set swapfile
set autoread
set updatetime=100
set tabpagemax=50

set title
set shortmess=aoOtTI
set wildmenu
set wildmode=longest:full,full

set viminfo='20,\"500,h
set history=1000

set sessionoptions-=blank
set sessionoptions-=options
set viewoptions-=options

set encoding=utf-8
scriptencoding utf-8
set fileencodings=utf-8,latin1,default
set fileformats=unix,dos,mac
set shiftwidth=4
set expandtab
set smarttab
set autoindent
set smartindent
set omnifunc=syntaxcomplete#Complete
set nojoinspaces

set nrformats-=octal

set formatoptions+=j

let showbreak='> '
set list
if (&termencoding ==# 'utf-8' || &encoding ==# 'utf-8') && v:version >= 700
  let &listchars="tab:\u21e5\u2010,trail:\u2022,extends:\u21c9,precedes:\u21c7,nbsp:\u2423"
  let &fillchars="vert:\u259a,fold:\u00b7"
else
  set listchars=tab:>-,trail:~,extends:>,precedes:<,nbsp:_
endif

set selection=inclusive
set virtualedit=block

set number
set relativenumber
set numberwidth=3
set cursorline
set ruler
set showcmd
set laststatus=2
set colorcolumn=120
set conceallevel=2

set hlsearch
set incsearch

set ignorecase
set smartcase

set scrolloff=3
set sidescroll=1
set sidescrolloff=5
set scrolljump=1
set display+=lastline,uhex

set completeopt=longest,menu

set diffopt+=vertical

set ttimeout
set ttimeoutlen=250

set mouse=

" }}}

" {{{ Autocommands

augroup no_relative_number_in_insert_mode
  autocmd!
  autocmd InsertEnter * set norelativenumber
  autocmd InsertLeave * set relativenumber
augroup END

" When editing a file, always jump to the last known cursor position.
" Don't do it when the position is invalid or when inside an event handler
" (happens when dropping a file on gvim).
augroup last_known_cursor_position
  autocmd BufReadPost *
        \ if line("'\"") > 0 && line("'\"") <= line("$") |
        \   exe "normal! g`\"" |
        \ endif
augroup END

augroup filetype_settings
  autocmd FileType go      setlocal shiftwidth=8 tabstop=8 noexpandtab
  autocmd FileType helm    setlocal shiftwidth=2 tabstop=2
  autocmd FileType json    setlocal foldmethod=syntax
  autocmd FileType jsonnet setlocal shiftwidth=2 tabstop=2
  autocmd FileType python  setlocal shiftwidth=4 tabstop=4
  autocmd FileType ruby    setlocal shiftwidth=2 tabstop=2
  autocmd FileType text    setlocal textwidth=120
  autocmd FileType yaml    setlocal shiftwidth=2 tabstop=2
augroup END

" }}}

" {{{ Plugins

" Airline
let g:airline_powerline_fonts=1
let g:airline_highlighting_cache=1

let g:airline_left_sep = ''
let g:airline_left_alt_sep = ''
let g:airline_right_sep = ''
let g:airline_right_alt_sep = ''
let g:airline_symbols = {
      \ 'branch': '',
      \ 'colnr': ' ',
      \ 'readonly': '󰌾',
      \ 'linenr': ' ',
      \ 'maxlinenr': '',
      \ 'dirty': ' '
      \ }

let g:airline_theme='nord'

let g:airline#extensions#tabline#enabled=1
let g:airline#extensions#tabline#show_buffers=0
let g:airline#extensions#tabline#show_close_button=0
let g:airline#extensions#tabline#show_tab_type=0

" bat (for fzf previews)
let $BAT_THEME = 'Nord'

" DevIcons
if exists('g:loaded_webdevicons')
  call webdevicons#refresh()
endif

" Man
runtime ftplugin/man.vim

augroup man_plugin_settings
  autocmd FileType man setlocal nolist
augroup END

" Match It
runtime macros/matchit.vim

" NERDTree
let NERDTreeIgnore=['\.pyc$', '\.zwc$', '\.zwc\.old$']
let NERDTreeMinimalUI=1
let g:NERDTreeDirArrowExpandable="\uF460"
let g:NERDTreeDirArrowCollapsible="\uF47C"

let g:DevIconsEnableFoldersOpenClose=1
let g:WebDevIconsNerdTreeBeforeGlyphPadding=''
let g:WebDevIconsUnicodeDecorateFolderNodes=1

highlight! link NERDTreeFlags NERDTreeDir

" NetRW
let g:netrw_http_cmd='curl -s -o'

" {{{ Mappings

inoremap jj <Esc>

nnoremap <silent> <C-n> :NERDTreeToggle<CR>
set pastetoggle=<Leader>p

" easy-align
nmap ga <Plug>(EasyAlign)
xmap ga <Plug>(EasyAlign)

" FZF / ripgrep
let $FZF_DEFAULT_COMMAND = 'fd --type file --hidden --exclude .git --strip-cwd-prefix'
set grepprg=rg\ --vimgrep\ --smart-case\ --hidden\ --follow
let g:rg_derive_root = 'true'
nnoremap <C-p> :Files<CR>
nnoremap <Leader>b :Buffers<CR>
nnoremap <Leader>s :BLines<CR>
nnoremap <Leader>ft :Filetypes<CR>
nnoremap <Leader>rg :Rg <C-R><C-W><CR>
command! -bang -nargs=* Rg call fzf#vim#grep("rg --column --line-number --no-heading --color=always --smart-case --hidden --glob '!.git' -- ".fzf#shellescape(<q-args>), fzf#vim#with_preview(), <bang>0)
command! -bang -nargs=* RG call fzf#vim#grep2("rg --column --line-number --no-heading --color=always --smart-case --hidden --glob '!.git' -- ", <q-args>, fzf#vim#with_preview(), <bang>0)

function! FzfSpellSink(word)
  exe 'normal! "_ciw'.a:word
endfunction
function! FzfSpell()
  let suggestions = spellsuggest(expand('<cword>'))
  return fzf#run(fzf#wrap({'source': suggestions, 'sink': function('FzfSpellSink')}))
endfunction
nnoremap z= :call FzfSpell()<CR>

" Mapping selecting mappings
nmap <leader><tab> <plug>(fzf-maps-n)
xmap <leader><tab> <plug>(fzf-maps-x)
omap <leader><tab> <plug>(fzf-maps-o)

" Insert mode completion
imap <c-x><c-k> <plug>(fzf-complete-word)
imap <c-x><c-f> <plug>(fzf-complete-path)
imap <c-x><c-l> <plug>(fzf-complete-line)

" "" '' <> () [] {}
noremap! "" ""<esc>i
noremap! """ """"""<esc>hhi
noremap! '' ''<esc>i

noremap! << <><esc>i
noremap! </ </><esc>i
noremap! <</ </><esc>hi
noremap! <<! <!--  --><esc>hhhi
noremap! <% <%  %><esc>hhi
noremap! <%= <%=  %><esc>hhi

noremap! (( ()<left>
noremap! (<cr> (<cr>)<c-o>O
noremap! (; ();<esc>hi
noremap! (<cr>; (<cr>);<c-o>O
noremap! ('; ('');<esc>hhi
noremap! ("; ("");<esc>hhi
noremap! (' ('')<esc>hi
noremap! (" ("")<esc>hi

noremap! {{ {}<left>
noremap! {<cr> {<cr>}<c-o>O
noremap! {; {};<esc>hi
noremap! {<cr>; {<cr>};<c-o>O
noremap! {'; {''};<esc>hhi
noremap! {"; {""};<esc>hhi
noremap! {' {''}<esc>hi
noremap! {" {""}<esc>hi
noremap! {# {#  #}<esc>hhi
noremap! {% {%  %}<esc>hhi
noremap! {{% {{  }}<esc>hhi

noremap! [[ []<left>
noremap! [<cr> [<cr>]<c-o>O
noremap! [; [];<esc>hi
noremap! [<cr>; [<cr>];<c-o>O
noremap! ['; [''];<esc>hhi
noremap! ["; [""];<esc>hhi
noremap! [' ['']<esc>hi
noremap! [" [""]<esc>hi

nnoremap <silent> <C-L> :nohlsearch<C-R>=has('diff')?'<Bar>diffupdate':''<CR><CR><C-L>

" }}}

" {{{ Local configuration

if filereadable($XDG_CONFIG_HOME.'/vim/local.vim')
  source ${XDG_CONFIG_HOME}/vim/local.vim
endif

" }}}

" vim:ft=vim:sw=2:ts=2:et:fdm=marker:
