#!/bin/sh

if [ `uname -s` = "FreeBSD" ]; then
    MIXER_COMMAND="mixer vol"
    MIXER_UP="+5"
    MIXER_DOWN="-5"
    MIXER_MUTE=""
else
    MIXER_COMMAND="amixer -D pulse sset Master"
    MIXER_UP="5%+"
    MIXER_DOWN="5%-"
    MIXER_MUTE="toggle"
fi

usage() {
    echo "Usage: $0 up|down|mute" >&2
    exit 1
}

_mixer() {
    $MIXER_COMMAND $1 >/dev/null 2>&1
}

[ $# -ne 1 ] && usage

case $1 in
    up)   _mixer $MIXER_UP ;;
    down) _mixer $MIXER_DOWN ;;
    mute) [ -n "$MIXER_MUTE" ] && _mixer toggle ;;
    *) usage ;;
esac
