#!/bin/sh

# Try to run py3status, or fallback on i3status

# To install it:
# pip install --user py3status requests

set -e

PY3STATUS_MODULES="${HOME}/.i3/py3status-modules"
PY3STATUS="py3status"
I3STATUS="i3status"

config="${HOME}/.i3/i3status.conf"
if [ -f "${config}.local" ]; then
    config="${config}.local"
fi

if type ${PY3STATUS} >/dev/null; then
    exec ${PY3STATUS} -c "${config}" -i "${PY3STATUS_MODULES}"
else
    exec ${I3STATUS} -c "${config}"
fi
