#!/bin/sh

WALLPAPER="$HOME/.i3/wallpaper"

if type nitrogen >/dev/null 2>&1; then
    nitrogen --restore
elif type feh >/dev/null 2>&1 && [ -f "$WALLPAPER" ]; then
    feh --bg-fill "$WALLPAPER"
fi

exit 0
