#!/bin/sh

mode=$1

[ -z "$mode" ] && mode=mono

main_screen=
alt_screen=

if [ `hostname -s` = 'alderaan' ]; then
    main_screen="DVI-I-2"
    alt_screen="DVI-I-3"
fi

if [ -n "$main_screen" -a -n "$alt_screen" ]; then
    if [ "$mode" = "mono" ]; then
        xrandr --output "$main_screen" --auto --output "$alt_screen" --off
    elif [ "$mode" = "dual" ]; then
        xrandr --output "$main_screen" --auto --output "$alt_screen" --auto --right-of "$main_screen"
    fi
fi

exit 0
