[icons]
name = "awesome"

[theme]
name = "nord-dark"
[theme.overrides]
alternating_tint_bg = "#3B4252"
alternating_tint_fg = "#2E3440"
# https://github.com/greshake/i3status-rust/issues/246#issuecomment-1086749777
separator = "<span font='13.5'>\ue0b2</span>"

[[block]]
block = "cpu"
interval = 1
format = "{barchart} {utilization}"

[[block]]
block = "load"
interval = 1
format = "{1m}"

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{mem_total_used_percents}"
format_swap = "{swap_used_percents}"
interval = 5
clickable = false

[[block]]
block = "sound"

[[block]]
block = "battery"
interval = 10
format = "{percentage} {time} ({power})"
full_format = "{percentage} {time}"
hide_missing = true

[[block]]
block = "time"
interval = 1
format = "%a %d %b %Y %H:%M"
