#!/bin/sh

: "${XDG_CONFIG_HOME:=${HOME}/.config}"
# shellcheck source=/dev/null
. "${ENV:-${XDG_CONFIG_HOME}/sh/profile}"

echo ' Creating necessary root-level dotfiles symlinks...'
mkdir -pv "${HOME}/.ssh"
ln -fsv .config/sh/profile "${HOME}/.profile"
ln -fsv .config/zsh/.zshenv "${HOME}/.zshenv"
ln -fsv ../.config/ssh/config "${HOME}/.ssh/config"
if [ "$(uname -s)" = 'Linux' ]; then
  ln -fsv .config/X11/xsessionrc "${HOME}/.xsessionrc"
fi

# yadm

echo ' Updating yadm repository configuration...'
yadm gitconfig commit.gpgSign true
yadm remote set-url origin https://gitlab.com/peikk0/dotfiles.git
yadm remote set-url --push origin git@gitlab.com:peikk0/dotfiles.git

# Homebrew

if [ "$(uname -s)" = 'Darwin' ]; then
  brewfile="${XDG_CONFIG_HOME}/homebrew/Brewfile"
  brewfile_lock_json="${brewfile}.lock.json"
  # shellcheck disable=SC3013
  if ! [ -f "${brewfile_lock_json}" ] || [ "${brewfile}" -nt "${brewfile_lock_json}" ]; then
    echo '🍺Updating Homebrew bundle...'
    brew bundle --file "${brewfile}" --verbose
  fi
  unset brewfile brewfile_lock_json

  if ! [ -L "${XDG_DATA_HOME}/terminfo/t/tmux-256color" ]; then
    echo ' Installing modified Tmux terminfo file for OSX...'
    mkdir -pv "${XDG_DATA_HOME}/terminfo/t"
    ln -fsv t "${XDG_DATA_HOME}/terminfo/74"
    ln -fsv "${XDG_CONFIG_HOME}/tmux/terminfo/tmux-256color" "${XDG_DATA_HOME}/terminfo/t/tmux-256color"
  fi
fi

# SSH

echo ' Updating SSH authorized keys...'
cat "${XDG_CONFIG_HOME}/ssh/authorized_keys"/* >"${HOME}/.ssh/authorized_keys"

# Tmux

if command -v tmux >/dev/null 2>&1; then
  if ! [ -d "${XDG_DATA_HOME}/tmux/plugins/tpm" ]; then
    echo ' Installing Tmux Plugin Manager...'
    git clone --quiet --depth=1 https://github.com/tmux-plugins/tpm.git \
      "${XDG_DATA_HOME}/tmux/plugins/tpm"
  else
    echo ' Ensuring Tmux Plugin Manager is up-to-date...'
    git -C "${XDG_DATA_HOME}/tmux/plugins/tpm" pull --quiet
  fi
  echo ' Installing all Tmux plugins...'
  "${XDG_DATA_HOME}/tmux/plugins/tpm/bin/install_plugins"
  echo ' Updating all Tmux plugins...'
  "${XDG_DATA_HOME}/tmux/plugins/tpm/bin/update_plugins" all
fi

# Vim

if command -v vim >/dev/null 2>&1; then
  if ! [ -f "${XDG_DATA_HOME}/vim/autoload/plug.vim" ]; then
    echo ' Setting up vim-plug...'
    curl -sfLo "${XDG_DATA_HOME}/vim/autoload/plug.vim" --create-dirs \
      https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  else
    echo ' Ensuring vim-plug is up-to-date...'
    vim -es -N -u "${XDG_CONFIG_HOME}/vim/vimrc" -i NONE '+PlugUpgrade' '+qall'
  fi

  echo ' Updating all Vim plugins...'
  vim -es -N -u "${XDG_CONFIG_HOME}/vim/vimrc" -i NONE '+PlugClean!' '+PlugUpdate' '+qall'
fi

if command -v fish >/dev/null 2>&1; then
  echo '  Installing fisher...'
  fish -c 'curl -sL https://raw.githubusercontent.com/jorgebucaran/fisher/main/functions/fisher.fish | source && fisher install jorgebucaran/fisher'
  echo '  Installing/updating all fish plugins...'
  fish -c 'fisher update'
fi

# ZSH

if command -v zsh >/dev/null 2>&1; then
  if ! [ -d "${XDG_DATA_HOME}/zsh/antidote" ]; then
    echo ' Installing antidote...'
    git clone --quiet --depth=1 https://github.com/mattmc3/antidote.git \
      "${XDG_DATA_HOME}/zsh/antidote"
  else
    echo ' Ensuring antidote is up-to-date...'
    git -C "${XDG_DATA_HOME}/zsh/antidote" pull --quiet
  fi
fi

# vim:filetype=sh:tabstop=2:shiftwidth=2:fdm=marker:
