# {{{ Vi Mode

ZVM_KEYTIMEOUT=0.1

ZVM_VI_INSERT_ESCAPE_BINDKEY=jj

ZVM_INSERT_MODE_CURSOR="${ZVM_CURSOR_BLINKING_UNDERLINE}"
ZVM_NORMAL_MODE_CURSOR="${ZVM_CURSOR_BLOCK}"
ZVM_OPPEND_MODE_CURSOR="${ZVM_CURSOR_BLINKING_UNDERLINE}"
ZVM_REPLACE_MODE_CURSOR="${ZVM_CURSOR_BLINKING_UNDERLINE}"
ZVM_VISUAL_MODE_CURSOR="${ZVM_CURSOR_BLOCK}"
ZVM_VISUAL_LINE_MODE_CURSOR="${ZVM_CURSOR_BLOCK}"

ZVM_VI_HIGHLIGHT_FOREGROUND='#e5e9f0'
ZVM_VI_HIGHLIGHT_BACKGROUND='#434c5e'

zvm_after_init_commands=(
  "zvm_bindkey viins '^W' vi-backward-kill-word"
)

# }}}

# vim:filetype=zsh:tabstop=2:shiftwidth=2:fdm=marker:
