# shellcheck shell=bash

# {{{ Includes

: "${XDG_CONFIG_HOME:=${HOME}/.config}"
# shellcheck source=/dev/null
. "${ENV:-${XDG_CONFIG_HOME}/sh/profile}"

# }}}

# {{{ Initial check

# Test for an interactive shell.  There is no need to set anything
# past this point for scp and rcp, and it's important to refrain from
# outputting anything in those cases.
if [[ $- != *i* ]]; then
  # Shell is non-interactive.  Be done now!
  return
fi

# }}}

# {{{ History

: "${XDG_STATE_HOME:=${HOME}/.local/state}"
mkdir -p "${XDG_STATE_HOME}/bash"
HISTFILE="${XDG_STATE_HOME}/bash/history"
HISTFILESIZE=5000
HISTSIZE=5000
HISTCONTROL=ignoredups
shopt -s histappend
shopt -s cmdhist

# }}}

# vim:filetype=bash:tabstop=2:shiftwidth=2:fdm=marker:
